<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>My.XXX.Shared</AssemblyName>
    <RootNamespace>My.XXX.Shared</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentResults" />
  </ItemGroup>
</Project>
