<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>My.XXX.Data</RootNamespace>
    <AssemblyName>My.XXX.Data</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <NoWarn>1701;1702;CA1822;IDE0290</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;CA1822;IDE0290</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Interfaces\IRequestLogRepository.cs" />
    <Compile Remove="Repositories\RequestLogRepository.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\My.XXX.Infra\04My.XXX.Infra.csproj" />
  </ItemGroup>

</Project>
