<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>My.XXX.Data</RootNamespace>
    <AssemblyName>My.XXX.Data</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <NoWarn>1701;1702;CA1822;IDE0290</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;CA1822;IDE0290</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Interfaces\IRequestLogRepository.cs" />
    <Compile Remove="Repositories\RequestLogRepository.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.2\contentFiles\any\any\LinqToDB.Templates\CopyMe.SqlServer.tt.txt" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.2\contentFiles\any\any\LinqToDB.Templates\DataAnnotations.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.2\contentFiles\any\any\LinqToDB.Templates\DataModel.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.2\contentFiles\any\any\LinqToDB.Templates\EditableObject.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.2\contentFiles\any\any\LinqToDB.Templates\Equatable.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.2\contentFiles\any\any\LinqToDB.Templates\Humanizer.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.2\contentFiles\any\any\LinqToDB.Templates\LinqToDB.SqlServer.SqlTypes.Tools.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.2\contentFiles\any\any\LinqToDB.Templates\LinqToDB.SqlServer.Tools.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.2\contentFiles\any\any\LinqToDB.Templates\LinqToDB.SqlServer.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.2\contentFiles\any\any\LinqToDB.Templates\LinqToDB.Tools.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.2\contentFiles\any\any\LinqToDB.Templates\LinqToDB.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.2\contentFiles\any\any\LinqToDB.Templates\MultipleFiles.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.2\contentFiles\any\any\LinqToDB.Templates\NotifyDataErrorInfo.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.2\contentFiles\any\any\LinqToDB.Templates\NotifyPropertyChanged.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.2\contentFiles\any\any\LinqToDB.Templates\ObsoleteAttributes.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.2\contentFiles\any\any\LinqToDB.Templates\PluralizationService.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.2\contentFiles\any\any\LinqToDB.Templates\T4Model.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.2\contentFiles\any\any\LinqToDB.Templates\Validation.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.3\contentFiles\any\any\LinqToDB.Templates\CopyMe.SqlServer.tt.txt" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.3\contentFiles\any\any\LinqToDB.Templates\DataAnnotations.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.3\contentFiles\any\any\LinqToDB.Templates\DataModel.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.3\contentFiles\any\any\LinqToDB.Templates\EditableObject.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.3\contentFiles\any\any\LinqToDB.Templates\Equatable.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.3\contentFiles\any\any\LinqToDB.Templates\Humanizer.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.3\contentFiles\any\any\LinqToDB.Templates\LinqToDB.SqlServer.SqlTypes.Tools.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.3\contentFiles\any\any\LinqToDB.Templates\LinqToDB.SqlServer.Tools.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.3\contentFiles\any\any\LinqToDB.Templates\LinqToDB.SqlServer.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.3\contentFiles\any\any\LinqToDB.Templates\LinqToDB.Tools.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.3\contentFiles\any\any\LinqToDB.Templates\LinqToDB.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.3\contentFiles\any\any\LinqToDB.Templates\MultipleFiles.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.3\contentFiles\any\any\LinqToDB.Templates\NotifyDataErrorInfo.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.3\contentFiles\any\any\LinqToDB.Templates\NotifyPropertyChanged.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.3\contentFiles\any\any\LinqToDB.Templates\ObsoleteAttributes.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.3\contentFiles\any\any\LinqToDB.Templates\PluralizationService.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.3\contentFiles\any\any\LinqToDB.Templates\T4Model.ttinclude" />
    <None Remove="C:\Users\Forres Jiang\.nuget\packages\linq2db.sqlserver\3.4.3\contentFiles\any\any\LinqToDB.Templates\Validation.ttinclude" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\My.XXX.Infra\04My.XXX.Infra.csproj" />
  </ItemGroup>

</Project>
