<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>My.XXX.Persistences</RootNamespace>
        <AssemblyName>My.XXX.Persistences</AssemblyName>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <DebugType>none</DebugType>
        <DebugSymbols>false</DebugSymbols>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\My.XXX.Services\02My.XXX.Services.csproj" />
        <ProjectReference Include="..\My.XXX.Shared\05My.XXX.Shared.csproj" />
        <ProjectReference Include="../My.XXX.Contracts/04My.XXX.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Riok.Mapperly" PrivateAssets="all" />
        <PackageReference Include="linq2db.Extensions" />
        <PackageReference Include="linq2db.SqlServer" />
        <PackageReference Include="Microsoft.Data.SqlClient" />
        <PackageReference Include="Npgsql" />
        <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    </ItemGroup>

    <PropertyGroup>
        <DisableImplicitContentFiles>true</DisableImplicitContentFiles>
    </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations/*.sql" />
  </ItemGroup>

</Project>
